apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/hoangthainguyen4121/udagram-api-user:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: backend-user